root:
- any: ['!{frontend,backend,common}/**/*', '!{frontend,backend,common}/*']

frontend:
  - frontend/**/*
  - frontend/*

backend:
  - backend/**/*
  - backend/*

common:
  - common/**/*
  - common/*
